apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: david
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:region:account-id:certificate/certificate-id"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
  labels:
    app: api 
spec:
  selector:
    app: api  
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
  type: LoadBalancer